[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/rumination/*"
  to = "/rumination/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signal.xml"
  to = "/.netlify/functions/signal-rss"
  status = 200

[functions."signal-scheduled"]
  schedule = "30 22 * * *"
